Check this
javaGuruBY/JIS1 pull request #10
Opened 2020-03-01 19:14 UTC by Enotik-code

2020-03-03 20:21 UTC, vladis1350 commented on homework/Kupreichik Anton/HomeWork_1/ex1_Counter/com.company/bean/main
> +    }
Условие: Если результат сложения текущего состояния счетчика и шага больше 100, тогда операцию не выполнять;

2020-03-03 20:21 UTC, vladis1350 commented on homework/Kupreichik Anton/HomeWork_1/ex1_Counter/com.company/bean/main
> +    }
Условие: Если результат вычитания текущего состояния счетчика от шага меньше 0, тогда операцию не выполнять;

2020-03-03 21:59 UTC, a-vov4eg commented on homework/Kupreichik Anton/HomeWork_1/ex2_Book/com.company/bean/main
> +        for (int i = 0; i < numberOfBooks; i += 1) {
лучше вместо "i += 1" использовать "i++"

2020-03-14 15:07 UTC, javaGuruBY requested changes
left comment

2020-03-14 15:07 UTC, javaGuruBY commented on homework/Kupreichik Anton/HomeWork_1/ex3_TV/com.company/test/TVTest.java
> +        int expectedResult = tv.getCurrentChanel() +1;
expected result should be independent

2020-03-14 15:07 UTC, javaGuruBY commented on homework/Kupreichik Anton/HomeWork_1/ex5_CreditCard/com.company/service/CreditCard.java
> +package com.company.service;
посмотри, какой Вове комментарий я оставил к этому занятию .
переделай

2020-03-22 16:59 UTC, javaGuruBY commented on homework/Kupreichik Anton/HomeWork_1/ex4_TVController/com.company/bean/main.java
> +                                if (tvController.isSwitchedOnOff(Philips) == false) {
инкапсулировать в методы

2020-03-22 17:01 UTC, javaGuruBY commented on homework/Kupreichik Anton/HomeWork_1/ex4_TVController/com.company/bean/main.java
> +                            case 1:
Move to psfs

2020-03-25 17:53 UTC, closed without merging