KupreichikA hw5 ex5
javaGuruBY/JIS1 pull request #107
Opened 2020-03-28 13:59 UTC by Enotik-code

2020-03-28 15:03 UTC, TLittleProgrammer submitted a review, later dismissed
lgfm

2020-03-28 15:03 UTC, Bell-Kranal commented on homework/Kupreichik Anton/HomeWork_5/ex5_CreditCard/service/CreditCardService.java
> +        if (!checkPin(creditCard, pin)) {
Можно разбить на несколько методов

2020-03-28 16:08 UTC, vladis1350 commented on homework/Kupreichik Anton/HomeWork_5/ex5_CreditCard/bean/CreditCard.java
> +public class CreditCard extends CreditCardService implements Serializable {
зачем ты тут наследуешь от сервиса?

2020-03-28 16:11 UTC, vladis1350 commented on homework/Kupreichik Anton/HomeWork_5/ex5_CreditCard/service/CreditCardService.java
> +        if (!checkPin(creditCard, pin)) {
Да, инкапсулируй, и лучше создай в сервисе объект карты и в конструкторе инициализируй, что бы не передавать карту как аргумент в каждом методе.

2020-03-28 16:12 UTC, vladis1350 reviewed
See my comments

2020-04-01 19:10 UTC, javaGuruBY requested changes
It looks like this job is unfinished. Please, check.

2020-04-01 19:10 UTC, javaGuruBY commented on homework/Kupreichik Anton/HomeWork_5/ex5_CreditCard/service/CreditCardService.java
> +        if (!checkPin(creditCard, pin)) {
Антон по сути сделал утилитарный класс, в этом случае такие методы лучше сделать статик и закрыть дефолтный конструктор
private CreditCardService() {}

2020-04-04 13:28 UTC, closed without merging