Bladyko danila hm6 task5
javaGuruBY/JIS1 pull request #15
Opened 2020-03-02 15:19 UTC by Bell-Kranal

2020-03-04 10:26 UTC, vladis1350 submitted a review, later dismissed
lgfm

2020-03-14 13:11 UTC, javaGuruBY approved these changes
lgfm

2020-03-14 14:28 UTC, javaGuruBY requested changes
I couldn't find it completed.
See what I wrote to vov4eg

2020-03-25 17:56 UTC, javaGuruBY approved these changes
lgfm

2020-03-25 17:56 UTC, merged