Bladyko danila hm7 task5
javaGuruBY/JIS1 pull request #39
Opened 2020-03-06 19:37 UTC by Bell-Kranal

2020-03-06 20:00 UTC, vladis1350 submitted a review, later dismissed
Lgfm

2020-03-14 16:58 UTC, javaGuruBY requested changes
left comment, 
merging conflict should be resolved

2020-03-14 16:58 UTC, javaGuruBY commented on homework/Bladyko Danila/src/by/jrr/bean/Car.java
> +                break;
не понимаю смысла этого цикла

2020-03-22 19:04 UTC, Bell-Kranal commented on homework/Bladyko Danila/src/by/jrr/bean/Car.java
> +                break;
check documentation

2020-03-23 18:13 UTC, vladis1350 approved these changes

2020-03-28 16:03 UTC, akupreychik approved these changes
lgfm

2020-03-28 16:54 UTC, a-vov4eg approved these changes

2020-03-28 16:54 UTC, a-vov4eg commented on homework/Bladyko Danila/src/by/jrr/bean/Car.java
> +        return false;
можно одной строкой
return this.currentSpeed < this.maxSpeed

тоже самое для двух методов выше

2020-04-01 16:03 UTC, javaGuruBY approved these changes

2020-04-01 16:03 UTC, merged