Vladis Urbanski hw5task4 review please
javaGuruBY/JIS1 pull request #4
Opened 2020-02-28 14:44 UTC by vladis1350

2020-02-28 17:51 UTC, TLittleProgrammer approved these changes
lgfm

2020-03-14 14:43 UTC, javaGuruBY requested changes
boolean login(User user, String password) {
  isEnteredPasswordEqualWithUserPassword(user, password) {
    dropAccessTriesCounter();
    return true;   
} else {
    decreaseAccessTriesCounter();
    isUserShouldBlocked();
}


пошарь коллегам

2020-03-14 14:43 UTC, javaGuruBY commented on homework/Vladislav Urbanski/less-1 edit test/ex4_Stock/src/com/vladis1350/App.java
> +        stokTest.testShouldInfoCompanyAfterOneUpdate();
test should WAT?

2020-03-14 14:43 UTC, javaGuruBY commented on homework/Vladislav Urbanski/less-1 edit test/ex5_UserLoginService/src/com/vladis1350/bean/User.java
> +    public boolean isUserAccess() {
isUserHasAcces ?

2020-03-14 14:43 UTC, javaGuruBY commented on homework/Vladislav Urbanski/less-1 edit test/ex5_UserLoginService/src/com/vladis1350/service/UserLoginService.java
> +package com.vladis1350.service;
Did I showed you how to wrote login service? 
Did I asked to re-write this?

2020-03-22 17:16 UTC, closed without merging