Danila bladyko hm8 task3
javaGuruBY/JIS1 pull request #47
Opened 2020-03-08 08:45 UTC by Bell-Kranal

2020-03-08 14:41 UTC, vladis1350 submitted a review, later dismissed
lgfm

2020-03-14 17:33 UTC, javaGuruBY requested changes
merge conflict should be resolved

2020-03-14 17:33 UTC, javaGuruBY commented on homework/Bladyko Danila/src/by/jrr/bean/Palindrome.java
> +            if(arrayOfChars[i] != arrayOfChars[size - i - 1]) {
looks complicated

2020-03-14 17:33 UTC, javaGuruBY commented on homework/Bladyko Danila/src/by/jrr/test/PalindromeTest.java
> +        checkGoodAnswer(actualFirstResult, expectedResult, "Test 1");
test 1-2-3-4-5-6-7-? 
give meaningful names

2020-03-25 08:08 UTC, vladis1350 approved these changes
lgfm

2020-03-25 18:19 UTC, javaGuruBY approved these changes
lgfm

2020-03-25 18:19 UTC, merged