Avseenkov V HomeWork7 Ex1 LookupArray
javaGuruBY/JIS1 pull request #50
Opened 2020-03-09 19:39 UTC by a-vov4eg

I learned how to write correct title. I full of shame for my last 6 titles. Seriosly.

2020-03-10 19:59 UTC, TLittleProgrammer requested changes
lgfm, but you hane eny little mistakes

2020-03-10 19:59 UTC, Bell-Kranal commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Service/LookupArrayService.java
> +            return 0;
Должно возвращать -1

2020-03-10 19:59 UTC, Bell-Kranal commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Service/LookupArrayService.java
> +            return 0;
Должно возвращать -1

2020-03-10 20:14 UTC, a-vov4eg commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Service/LookupArrayService.java
> +            return 0;
fixed

2020-03-10 20:15 UTC, a-vov4eg commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Service/LookupArrayService.java
> +            return 0;
fixed

2020-03-14 17:27 UTC, javaGuruBY approved these changes
left some comments, otherwise lgfm

2020-03-14 17:27 UTC, javaGuruBY commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Service/LookupArrayDemo.java
> +        int[] array0 = {1, 2, 3, 4, 5, 4, 3, 2, 0};
give meaningful name to arrays

2020-03-14 17:27 UTC, javaGuruBY commented on homework/Avseenkov V/HomeWork7/Ex1_LookUpArrayService/Test/LookupArrayTest.java
> +public class LookupArrayTest {
test?

2020-03-22 18:53 UTC, akupreychik approved these changes
lgfm

2020-03-22 18:56 UTC, vladis1350 approved these changes
Lgfm

2020-03-28 14:49 UTC, TLittleProgrammer approved these changes
lgfm

2020-03-28 14:49 UTC, merged