Danila hm9 task2
javaGuruBY/JIS1 pull request #59
Opened 2020-03-10 19:44 UTC by Bell-Kranal

2020-03-23 18:30 UTC, vladis1350 submitted a review, later dismissed
Lgfm

2020-03-25 18:40 UTC, javaGuruBY requested changes
left a comment

2020-03-25 18:40 UTC, javaGuruBY commented on homework/Danila/Shape/src/by/jrr/abstracts/AbstractShape.java
> +        return null;
looks like you missed something, please, do review

2020-03-28 16:03 UTC, a-vov4eg approved these changes
лгфм

2020-03-28 16:03 UTC, a-vov4eg commented on homework/Danila/Shape/src/by/jrr/abstracts/AbstractShape.java
> +    int width;
лучше тоже даблами сделать

2020-03-28 16:03 UTC, a-vov4eg commented on homework/Danila/Shape/src/by/jrr/figures/Circle.java
> +        return Math.PI * this.radius * this.radius;
Компактнее будет return Math.PI * Math.pow(this.radius, 2);

2020-04-01 16:07 UTC, merged