Danila bladyko hm5 task3
javaGuruBY/JIS1 pull request #8
Opened 2020-02-28 19:24 UTC by Bell-Kranal

2020-02-28 19:30 UTC, vladis1350 approved these changes
lgfm

2020-02-29 12:32 UTC, Enotik-code commented
lgfm

2020-03-08 14:29 UTC, javaGuruBY requested changes

2020-03-08 14:29 UTC, javaGuruBY commented on homework/Bladyko Danila/HomeWork_03/by/jrr/src/by/jrr/main_user/User.java
> +    public User(String s, String s1) {
String s, String s1
variable names should be self-explanatory

2020-03-08 14:29 UTC, javaGuruBY commented on homework/Bladyko Danila/HomeWork_03/by/jrr/src/by/jrr/main_user/User.java
> +    public void password(String pass) {
[ ] - use javaBeans convention for such methods.

2020-03-08 14:29 UTC, javaGuruBY commented on homework/Bladyko Danila/HomeWork_03/by/jrr/src/by/jrr/service/UserLoginService.java
> +            user.loginAttemptsBeforeBlocking++;
this will increase counter with every successful login. 
[ ] - Use dropCounter() instead

2020-03-08 14:29 UTC, javaGuruBY commented on homework/Bladyko Danila/HomeWork_03/by/jrr/src/by/jrr/tests/UserServiceTest.java
> +package by.jrr.tests;
this test won't work. Ask colleagues for help
Create a new one test using best practices that we discussed

2020-03-08 14:30 UTC, javaGuruBY commented
> lgfm

re-review, please.

2020-03-08 14:30 UTC, javaGuruBY commented
> lgfm

re-review, please.

2020-03-22 17:06 UTC, closed without merging